name: Deploy ID Website-Live

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.PROD_SERVER_HOST }}
          username: ${{ vars.PROD_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/production/ID-Website
            git pull origin main
            npm ci
            npm run build
            sudo systemctl reload nginx

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.PROD_SERVER_HOST }}
          username: ${{ vars.PROD_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/staging/ID-Website
            git pull origin staging
            npm ci
            npm run build
            sudo systemctl reload nginx